CREATE DATABASE `hatbazar`;

CREATE TABLE `user`(`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR (100), `address` VARCHAR (100), `email` VARCHAR (50), `phone` VARCHAR (15), `username` VARCHAR (25) NOT NULL UNIQUE KEY, `password` VARCHAR (20) NOT NULL);
CREATE TABLE `role`(`id` INT AUTO_INCREMENT PRIMARY KEY , `role_name` VARCHAR (50) NOT NULL UNIQUE KEY);